"""Domain entities and the status model (DESIGN.md §2.7, §1.1, §1.15).

Seven entity types. Every one carries `id`, `version`, `status`, `created_at`,
`updated_at`, `created_by`, `updated_by`, `history[]`. `status` is declared per
entity rather than on the shared base, because each entity has its own status
vocabulary and its own legal-transition matrix (see `transitions.py`) — a bare
`status: str` on the base would let a caller assign a status value from the
wrong entity's vocabulary and have Pydantic wave it through.

Two things must not regress here (§1.1, and the trap called out in T02):

1. **No numeric confidence, anywhere.** `confidence` is a three-value enum with
   a required, non-empty `confidence_basis`. HIGH = user said it. MEDIUM =
   strongly implied. LOW = agent inferred. If a percentage is ever wanted for a
   dashboard, map the enum to a fixed number in the presentation layer — the
   model itself never emits one.
2. **`Unknown.blocking` and `Unknown.route` stay separate fields.** Merging
   them into one `classification` enum makes "blocking *and* needs research" —
   a common case — unrepresentable, and breaks the readiness gate rule (T10).
"""

from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from typing import Any, ClassVar, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

# ---------------------------------------------------------------------------
# Shared primitives every entity is built from.
# ---------------------------------------------------------------------------

Confidence = Literal["HIGH", "MEDIUM", "LOW"]
"""No percentages anywhere (§1.1). 72% and 68% are indistinguishable in
practice and will be generated by vibes; the enum is checkable against what
the user actually said, a number never is."""


class EntityType(str, Enum):
    """One member per ledger entity kind. Question and Answer share a record
    and therefore a single type — they are distinguished at the ID-series
    level (`Q-nnn` / `ANS-nnn`), not the type level."""

    REQUIREMENT = "requirement"
    ASSUMPTION = "assumption"
    DECISION = "decision"
    UNKNOWN = "unknown"
    QUESTION_ANSWER = "question_answer"
    RESEARCH_FINDING = "research_finding"
    RISK = "risk"


class HistoryEntry(BaseModel):
    """One recorded change to a single field on an entity. Entities are never
    edited silently — every status or value change appends one of these."""

    model_config = ConfigDict(extra="forbid")

    field: str
    old_value: Any = None
    new_value: Any = None
    changed_at: datetime
    changed_by: str
    reason: str | None = None


class ConfidenceMixin(BaseModel):
    """`confidence` and `confidence_basis`, together, always. A bare enum with
    no justification would be exactly as unaccountable as a percentage — the
    basis is what makes the value checkable, so it is required and non-empty,
    not optional (§1.1)."""

    confidence: Confidence
    confidence_basis: str

    @field_validator("confidence_basis")
    @classmethod
    def _basis_is_required(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError(
                "confidence_basis is required and must explain the confidence "
                "level — it cannot be empty or whitespace"
            )
        return v


class BaseEntity(BaseModel):
    """Fields every ledger entity carries, per §2.7.

    `extra="forbid"` on every entity: a field that is not part of the declared
    schema is a bug to catch at construction time, not a value to silently
    accept. `Requirement.custom_fields` is the one deliberate escape hatch for
    house-style extensibility (T04) — a typed dict, not an open top level.
    """

    model_config = ConfigDict(extra="forbid")

    id: str
    version: int = Field(default=1, ge=1)
    created_at: datetime
    updated_at: datetime
    created_by: str
    updated_by: str
    history: list[HistoryEntry] = Field(default_factory=list)

    # Overridden per subclass. Not a pydantic field — a plain classmethod
    # consulted by the id validator below.
    _id_prefixes: ClassVar[tuple[str, ...]] = ()

    @field_validator("id")
    @classmethod
    def _id_matches_prefix(cls, v: str) -> str:
        prefixes = cls._id_prefixes
        if not prefixes:
            return v
        pattern = "|".join(re.escape(p) for p in prefixes)
        if not re.fullmatch(rf"(?:{pattern})-\d{{3,}}", v):
            wanted = " or ".join(f"{p}-nnn" for p in prefixes)
            raise ValueError(f"id must look like {wanted}, got {v!r}")
        return v


# ---------------------------------------------------------------------------
# The seven entities.
# ---------------------------------------------------------------------------


class Requirement(BaseEntity, ConfidenceMixin):
    """`REQ-nnn`. What the system must, should or could do."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("REQ",)

    status: Literal["PROPOSED", "CONFIRMED", "REJECTED", "SUPERSEDED"] = "PROPOSED"
    statement: str
    type: Literal["functional", "non_functional", "constraint"]
    covers_areas: list[str] = Field(default_factory=list)
    derived_from_answers: list[str] = Field(default_factory=list)
    depends_on_assumptions: list[str] = Field(default_factory=list)
    depends_on_decisions: list[str] = Field(default_factory=list)
    priority: Literal["must", "should", "could", "wont_v1"]
    needs_user_confirmation: bool = False
    custom_fields: dict[str, Any] = Field(default_factory=dict)


class Assumption(BaseEntity, ConfidenceMixin):
    """`ASM-nnn`. Something the agent inferred rather than was told, standing
    in for a requirement until confirmed or replaced."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("ASM",)

    status: Literal["PROPOSED", "CONFIRMED", "REJECTED", "SUPERSEDED"] = "PROPOSED"
    statement: str
    reason: str
    impact: Literal["HIGH", "MEDIUM", "LOW"]
    affects_requirements: list[str] = Field(default_factory=list)
    affects_areas: list[str] = Field(default_factory=list)
    user_confirmation_required: bool = False
    confirmed_at: datetime | None = None
    confirmed_by: str | None = None
    provisional: bool = False
    """True when pending external/client input (§6.2) — the assumption stands
    in until an outside party answers, not until the user does."""


AffectsKind = Literal["architecture", "scope", "other"]
"""DESIGN.md §1.13's tier rule for a blocking decision's expected-decision-
date keys on whether the decision "affects architecture" or "affects scope".
`Decision.affects` is the classification itself (resolved decision #21 —
previously `ppa/engines/dates.py::expected_decision_date` took this as a
caller-supplied argument because `Decision` carried no such field). `None`
means unclassified, which `expected_decision_date` treats as `"other"` (the
safe +14-day default), never a silent guess at "architecture" or "scope"."""


class Decision(BaseEntity):
    """`DEC-nnn`. An open question with a resolution path, distinct from an
    Unknown: a Decision is already framed as a choice among options."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("DEC",)

    status: Literal["OPEN", "DECIDE_LATER", "DECIDED", "SUPERSEDED"] = "OPEN"
    question: str
    blocking: bool = False
    affects: AffectsKind | None = None
    owner: str
    owner_type: Literal["user", "external", "agent"]
    identified_at: datetime
    expected_decision_date: datetime | None = None
    decided_at: datetime | None = None
    defer_reason: str | None = None
    options: list[str] = Field(default_factory=list)
    chosen_option: str | None = None
    rationale: str | None = None
    prerequisites: list[str] = Field(default_factory=list)
    current_assumption: str | None = None
    related_requirements: list[str] = Field(default_factory=list)
    related_research: list[str] = Field(default_factory=list)


class Unknown(BaseEntity):
    """`UNK-nnn`. Something not yet known. `blocking` and `route` are
    deliberately separate fields, not one `classification` enum — see the
    module docstring and the T02 trap. The readiness gate reads `blocking`;
    the router reads `route`. Conflating them makes "blocking AND needs
    research" unrepresentable."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("UNK",)

    status: Literal["OPEN", "RESOLVED", "CONVERTED"] = "OPEN"
    question: str
    area: str
    why_it_matters: str
    blocking: bool
    """Does this stop planning from reaching READY? Read by the readiness
    gate (T10). Orthogonal to `route`."""
    route: Literal["GUIDANCE", "RESEARCH", "USER_DECISION", "ASSUMPTION", "OPTIONAL", "FUTURE"]
    """How this gets resolved. Read by the router (T26). Orthogonal to
    `blocking` — a item can be blocking AND routed to RESEARCH at once."""
    owner_type: Literal["user", "external", "agent"]
    converted_to: str | None = None
    """Set when status becomes CONVERTED — the id of the entity this Unknown
    turned into (an Assumption, a Decision, ...)."""


class QuestionAnswer(BaseEntity):
    """`Q-nnn` / `ANS-nnn`. One record, two ID series: `Q-nnn` while awaiting
    an answer, `ANS-nnn` once one is recorded. Splitting Question and Answer
    into separate entities was rejected — an answer's entire meaning depends
    on the question it responds to, and duplicating that link across two
    entities is worse than one record with two allowed id shapes."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("Q", "ANS")

    status: Literal["PENDING", "ANSWERED", "REPLACED"] = "PENDING"
    text: str
    why_asked: str
    target_areas: list[str] = Field(default_factory=list)
    round: int = Field(ge=1)
    suggested_options: list[str] = Field(default_factory=list)
    recommended_default: str | None = None
    answer_kind: Literal["answered", "dont_know", "decide_later", "not_relevant"] | None = None
    dont_know_kind: str | None = None
    answer_text: str | None = None
    answered_at: datetime | None = None


class ResearchFinding(BaseEntity, ConfidenceMixin):
    """`RES-nnn`. What Research Mode found, with enough provenance to judge
    whether it still holds."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("RES",)

    status: Literal["ACTIVE", "REPLACED"] = "ACTIVE"
    question: str
    method: str
    summary: str
    options_found: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    researched_at: datetime
    stale_after_days: int = Field(default=90, ge=1)
    feeds_decision: str | None = None


class Risk(BaseEntity):
    """`RSK-nnn`. Declared now so the schema does not change when Planning
    lands in v2 — **not written in v1**. No Discovery tool creates a Risk;
    Planning owns it."""

    _id_prefixes: ClassVar[tuple[str, ...]] = ("RSK",)

    status: Literal["OPEN", "MITIGATED", "ACCEPTED", "CLOSED"] = "OPEN"
    statement: str
    likelihood: Literal["HIGH", "MEDIUM", "LOW"]
    impact: Literal["HIGH", "MEDIUM", "LOW"]
    area: str
    mitigation: str | None = None


ENTITY_TYPES: dict[EntityType, type[BaseEntity]] = {
    EntityType.REQUIREMENT: Requirement,
    EntityType.ASSUMPTION: Assumption,
    EntityType.DECISION: Decision,
    EntityType.UNKNOWN: Unknown,
    EntityType.QUESTION_ANSWER: QuestionAnswer,
    EntityType.RESEARCH_FINDING: ResearchFinding,
    EntityType.RISK: Risk,
}
"""The one place that maps an `EntityType` to its Pydantic model. Anything
that needs to go from "which kind of entity" to "which class" — the
materializer (T07), the registry (T13) — reads this rather than hand-rolling
its own if/elif chain."""
